version: 2.1
executors:
  default:
    docker:
      - image: circleci/python:3.8

jobs:
  build:
    executor: default
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build Docker Image
          command: |
            docker build -t my-nginx-app .
      - run:
          name: Authenticate and Push to Docker Hub
          command: |
            docker login -u "$DOCKER_USERNAME" -p "$DOCKER_ACCESS_TOKEN"
            docker tag my-nginx-app:latest $DOCKER_USERNAME/my-nginx-app:latest
            docker push $DOCKER_USERNAME/my-nginx-app:latest

workflows:
  version: 2
  build-deploy:
    jobs:
      - build

