version: 2.1
executors:
  default:
    docker:
      - image: circleci/python:3.8

jobs:
  lint:
    executor: default
    steps:
      - checkout
      - run:
          name: Run Linting
          command: |
            # Run your linting commands here
            # Example for Python using flake8:
            pip install flake8
            flake8 .

  build:
    executor: default
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build Docker Image
          command: |
            docker build -t my-nginx-app .
      - run:
          name: Authenticate and Push to Docker Hub
          command: |
            docker login -u "$DOCKER_USERNAME" -p "$DOCKER_ACCESS_TOKEN"
            docker tag my-nginx-app:latest $DOCKER_USERNAME/my-nginx-app:latest
            docker push $DOCKER_USERNAME/my-nginx-app:latest
  
  deploy-eks-blue:
    executor: default
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Authenticate to Docker Hub
          command: |
            docker login -u "$DOCKER_USERNAME" -p "$DOCKER_ACCESS_TOKEN"
      - run:
          name: Install kubectl and eksctl
          command: |
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            chmod +x kubectl
            sudo mv kubectl /usr/local/bin/
            curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
            sudo mv /tmp/eksctl /usr/local/bin
            pip install awscli
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set default.region $AWS_DEFAULT_REGION
            aws configure set aws_session_token $AWS_SESSION_TOKEN
      - run:
          name: Update kubectl configuration for EKS cluster
          command: |
            aws eks --region us-east-1 update-kubeconfig --name my-eks-cluster2
      - run:
          name: Deploy to EKS cluster
          command: |
            kubectl apply -f deployment-blue.yml
            kubectl apply -f service-blue.yml

  deploy-eks-green:
    executor: default
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Authenticate to Docker Hub
          command: |
            docker login -u "$DOCKER_USERNAME" -p "$DOCKER_ACCESS_TOKEN"
      - run:
          name: Install kubectl and eksctl
          command: |
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            chmod +x kubectl
            sudo mv kubectl /usr/local/bin/
            curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
            sudo mv /tmp/eksctl /usr/local/bin
            pip install awscli
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set default.region $AWS_DEFAULT_REGION
            aws configure set aws_session_token $AWS_SESSION_TOKEN
      - run:
          name: Update kubectl configuration for EKS cluster
          command: |
            aws eks --region us-east-1 update-kubeconfig --name my-eks-cluster2
      - run:
          name: Deploy to Green Environment
          command: |
            kubectl apply -f deployment-green.yml
            kubectl apply -f service-green.yml

  switch-to-green:
    executor: default
    steps:
      - checkout
      - run:
          name: Install kubectl and eksctl
          command: |
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            chmod +x kubectl
            sudo mv kubectl /usr/local/bin/
            curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
            sudo mv /tmp/eksctl /usr/local/bin
            pip install awscli
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set default.region $AWS_DEFAULT_REGION
            aws configure set aws_session_token $AWS_SESSION_TOKEN
      - run:
          name: Perform Blue to Green Switch
          command: |
            aws eks --region us-east-1 update-kubeconfig --name my-eks-cluster2
            kubectl config use-context arn:aws:eks:us-east-1:023550034014:cluster/my-eks-cluster2
            kubectl set image deployment/my-nginx-app-deployment-green my-nginx-app=juanlopez0114/my-nginx-app:green



workflows:
  version: 2
  blue-green-deploy:
    jobs:
      - lint
      - build:
          requires:
            - lint
      - deploy-eks-blue:
          requires:
            - build
      - deploy-eks-green:
          requires:
            - build
            - deploy-eks-blue
      - switch-to-green:
          requires:
            - deploy-eks-blue
            - deploy-eks-green

