version: 2.1
executors:
  default:
    docker:
      - image: circleci/python:3.8

jobs:

  lint:
    executor: default
    steps:
      - checkout
      - run:
          name: Run Linting
          command: |
            # Run your linting commands here
            # Example for Python using flake8:
            pip install flake8
            flake8 .

  build:
    executor: default
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build Docker Image
          command: |
            docker build -t my-nginx-app .
      - run:
          name: Authenticate and Push to Docker Hub
          command: |
            docker login -u "$DOCKER_USERNAME" -p "$DOCKER_ACCESS_TOKEN"
            docker tag my-nginx-app:latest $DOCKER_USERNAME/my-nginx-app:latest
            docker push $DOCKER_USERNAME/my-nginx-app:latest
  
  deploy-eks:
    executor: default
    steps:
      - checkout
      - run:
          name: Install kubectl and create eks cluster
          command: |
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            chmod +x kubectl
            eksctl create cluster --name my-eks-cluster --region us-east-1 --nodegroup-name ng-1 --nodes 2 --node-type t2.medium
      - run:
          name: Update kubectl configuration for EKS cluster
          command: |
            aws eks --region us-east-1 update-kubeconfig --name my-eks-cluster
      - run:
          name: Deploy to EKS cluster
          command: |
            kubectl apply -f deployment-blue.yaml
            kubectl apply -f service-blue.yaml

workflows:
  version: 2
  build-lint-deploy:
    jobs:
      - lint
      - build:
          requires:
            - lint
      - deploy-eks:
          requires:
            - build
